fly.toml Configuration

app = "tap-dash-game"  # You can change this to your preferred app name

# Choose a region close to your players for lower latency
primary_region = "iad"  # Washington D.C. - change as needed

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
