services:
  - type: web
    name: airline-route-ranker
    env: static
    buildCommand: npm install && npm run build:deploy
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PUBLIC_BACKEND_URL
        sync: false 