services:
  - type: web
    name: airline-route-ranker
    env: static
    buildCommand: npm install && npm run build:deploy
    staticPublishPath: ./build
    headers:
      - path: /_app/**/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      # Serve static assets directly
      - type: rewrite
        source: /_app/*
        destination: /_app/*
      # Any other routes fall back to index.html for SPA routing
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PUBLIC_BACKEND_URL
        sync: false 