services:
  - type: web
    name: flights-reliability-fe
    runtime: static
    buildCommand: npm install && npm run build:deploy
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PUBLIC_API_BASE_URL
        value: https://airline-route-reliability.onrender.com
      # API key should be set in Render dashboard
      # Make sure to use the same key as in your backend service
      - key: API_KEY
        sync: false 